version: '3.8'

services:
  cachier-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - cachier-service:/app
    restart: always

volumes:
  cachier-service: ~
